name: pip_clients_emailsettings
version: "1.0.0"
description: Clients for Email Settings microservice for Pip.Services in Dart. This microservice keeps settings of email recipients.
homepage: https://github.com/pip-services-users/pip-clients-emailsetings-dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  pip_services3_commons: ">=1.0.5 <2.0.0"
  pip_services3_components: ">=1.0.2 <2.0.0"
  pip_services3_data: ">=1.0.0 <2.0.0"
  pip_services3_rpc: ">=1.0.2 <2.0.0"
  pip_services_emailsettings: ">=1.0.1 <2.0.0"
  pip_clients_email: ">=1.0.0 <2.0.0"
  http: "^0.12.0"
  angel_framework: ^2.1.1

dev_dependencies:
  test: '>=1.14.2 <2.0.0'
